/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg5_brauliocalix;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogIn = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        USUlog = new javax.swing.JTextField();
        contralog = new javax.swing.JPasswordField();
        Credenciales = new javax.swing.JButton();
        Madmin = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        Cemple = new javax.swing.JButton();
        Dulceria = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        dulces = new javax.swing.JButton();
        Cpeli = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        NPeli = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        CreaPeli = new javax.swing.JButton();
        Aseo = new javax.swing.JDialog();
        CreaEmple = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        Nnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FechaEmple = new com.toedter.calendar.JDateChooser();
        NUsuario = new javax.swing.JTextField();
        CB_puesto = new javax.swing.JComboBox<>();
        CNemple = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CCorreo = new javax.swing.JTextField();
        CContra = new javax.swing.JTextField();
        CrearDulce = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Ndulc = new javax.swing.JTextField();
        Nsabor = new javax.swing.JTextField();
        CB_tipo = new javax.swing.JComboBox<>();
        CreaDulce = new javax.swing.JButton();
        Boleteria = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        btcrearpeli = new javax.swing.JButton();
        LOGINP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("INGRESE SUS CREDENCIALES");

        jLabel2.setText("USUARIO");

        jLabel5.setText("CONTRASEÑA");

        Credenciales.setText("INGRESAR");
        Credenciales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CredencialesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LogInLayout = new javax.swing.GroupLayout(LogIn.getContentPane());
        LogIn.getContentPane().setLayout(LogInLayout);
        LogInLayout.setHorizontalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(USUlog, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contralog, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LogInLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(Credenciales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LogInLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        LogInLayout.setVerticalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(USUlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contralog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(Credenciales)
                .addGap(27, 27, 27))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("ADMIN");

        Cemple.setText("CREAR EMPLEADO");
        Cemple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CempleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MadminLayout = new javax.swing.GroupLayout(Madmin.getContentPane());
        Madmin.getContentPane().setLayout(MadminLayout);
        MadminLayout.setHorizontalGroup(
            MadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MadminLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(MadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cemple)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        MadminLayout.setVerticalGroup(
            MadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MadminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Cemple)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jLabel14.setText("DULCERIA");

        dulces.setText("Crear nuevo dulce");
        dulces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dulcesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DulceriaLayout = new javax.swing.GroupLayout(Dulceria.getContentPane());
        Dulceria.getContentPane().setLayout(DulceriaLayout);
        DulceriaLayout.setHorizontalGroup(
            DulceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DulceriaLayout.createSequentialGroup()
                .addGroup(DulceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DulceriaLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel14))
                    .addGroup(DulceriaLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(dulces)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        DulceriaLayout.setVerticalGroup(
            DulceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DulceriaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(dulces)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jLabel18.setText("BOLETERIA");

        jLabel19.setText("Nombre");

        jLabel20.setText("duracion");

        jLabel21.setText("Clasificacion");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "terror", "comedia", "romance", "drama", "accion", "infantil" }));

        jLabel22.setText("categoria");

        CreaPeli.setText("Crear Pelicula");

        javax.swing.GroupLayout CpeliLayout = new javax.swing.GroupLayout(Cpeli.getContentPane());
        Cpeli.getContentPane().setLayout(CpeliLayout);
        CpeliLayout.setHorizontalGroup(
            CpeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CpeliLayout.createSequentialGroup()
                .addGroup(CpeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CpeliLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel18))
                    .addGroup(CpeliLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(CpeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CpeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19))
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(85, 85, 85)
                        .addGroup(CpeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 89, Short.MAX_VALUE)
                            .addComponent(NPeli)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)))
                    .addGroup(CpeliLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(CreaPeli)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        CpeliLayout.setVerticalGroup(
            CpeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CpeliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(29, 29, 29)
                .addGroup(CpeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(NPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(CpeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(CpeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(CpeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(46, 46, 46)
                .addComponent(CreaPeli)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AseoLayout = new javax.swing.GroupLayout(Aseo.getContentPane());
        Aseo.getContentPane().setLayout(AseoLayout);
        AseoLayout.setHorizontalGroup(
            AseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        AseoLayout.setVerticalGroup(
            AseoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel7.setText("Nombre ");

        jLabel8.setText("ingrese los datos del empleado");

        jLabel9.setText("Fecha de nacimiento");

        jLabel10.setText("puesto");

        jLabel11.setText("Correo");

        CB_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dulceria", "Boleteria", "Aseo" }));

        CNemple.setText("Crear Empleado");
        CNemple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CNempleMouseClicked(evt);
            }
        });

        jLabel12.setText("Nombre de usuario");

        jLabel13.setText("Contraseña");

        javax.swing.GroupLayout CreaEmpleLayout = new javax.swing.GroupLayout(CreaEmple.getContentPane());
        CreaEmple.getContentPane().setLayout(CreaEmpleLayout);
        CreaEmpleLayout.setHorizontalGroup(
            CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreaEmpleLayout.createSequentialGroup()
                .addGroup(CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreaEmpleLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel8))
                    .addGroup(CreaEmpleLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addGap(88, 88, 88)
                        .addGroup(CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CB_puesto, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                                .addComponent(NUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CCorreo))
                            .addComponent(FechaEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CContra, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CreaEmpleLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(CNemple)))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CreaEmpleLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel12)
                    .addContainerGap(363, Short.MAX_VALUE)))
        );
        CreaEmpleLayout.setVerticalGroup(
            CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreaEmpleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addGroup(CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Nnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(FechaEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(NUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CB_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(CNemple)
                .addGap(25, 25, 25))
            .addGroup(CreaEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CreaEmpleLayout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(jLabel12)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );

        jLabel15.setText("Nombre");

        jLabel16.setText("Sabor");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("tipo");

        CB_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolates", "Gomitas", "Paletas ", "Chicles" }));

        CreaDulce.setText("Crear Dulce");
        CreaDulce.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CreaDulceKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout CrearDulceLayout = new javax.swing.GroupLayout(CrearDulce.getContentPane());
        CrearDulce.getContentPane().setLayout(CrearDulceLayout);
        CrearDulceLayout.setHorizontalGroup(
            CrearDulceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearDulceLayout.createSequentialGroup()
                .addGroup(CrearDulceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearDulceLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(CrearDulceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(CrearDulceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(93, 93, 93)
                        .addGroup(CrearDulceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ndulc)
                            .addComponent(Nsabor)
                            .addComponent(CB_tipo, 0, 95, Short.MAX_VALUE)))
                    .addGroup(CrearDulceLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(CreaDulce)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        CrearDulceLayout.setVerticalGroup(
            CrearDulceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearDulceLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(CrearDulceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Ndulc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(CrearDulceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Nsabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(CrearDulceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CB_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(CreaDulce)
                .addGap(42, 42, 42))
        );

        jLabel23.setText("BOLETERIA");

        btcrearpeli.setText("Crear Pelicula");
        btcrearpeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcrearpeliMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BoleteriaLayout = new javax.swing.GroupLayout(Boleteria.getContentPane());
        Boleteria.getContentPane().setLayout(BoleteriaLayout);
        BoleteriaLayout.setHorizontalGroup(
            BoleteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoleteriaLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(BoleteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btcrearpeli)
                    .addGroup(BoleteriaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel23)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        BoleteriaLayout.setVerticalGroup(
            BoleteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoleteriaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel23)
                .addGap(31, 31, 31)
                .addComponent(btcrearpeli)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOGINP.setText("LOGIN");
        LOGINP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGINPMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("BIENVENIDO A CINEPOLIS");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("LOG IN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(LOGINP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(jLabel6)
                    .addContainerGap(301, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(LOGINP)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(193, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(61, 61, 61)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGINPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINPMouseClicked
        LogIn.setModal(true);//no deja salirse
        LogIn.pack();
        LogIn.setLocationRelativeTo(this);
        LogIn.setVisible(true);
    }//GEN-LAST:event_LOGINPMouseClicked

    private void CredencialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CredencialesMouseClicked
        // USUlog contralog
        String Usu = USUlog.getText();
        String contra = contralog.getText();
        String cargo = "";
        String nombre = "";
        if (Usu.equals("admin") && contra.equals("admin")) {
            Madmin.setModal(true);//no deja salirse
            Madmin.pack();
            Madmin.setLocationRelativeTo(this);
            Madmin.setVisible(true);
        } else {
            for (int i = 0; i < emple.size(); i++) {
                if (Usu.equals(emple.get(i).getUsuario()) && contra.equals(emple.get(i).getContra())) {
                    cargo = emple.get(i).getPuesto();
                    nombre = emple.get(i).getNombre();
                    System.out.println(cargo);
                    System.out.println(nombre);
                }
            
            
            if (cargo.equals("Dulceria")) {
                System.out.println(cargo);
                Dulceria.setModal(true);
                Dulceria.pack();
                Dulceria.setLocationRelativeTo(CreaEmple);
                Dulceria.setVisible(true);
            } else if (cargo.equals("Boleteria")) {
                System.out.println(cargo);
                Boleteria.setModal(true);
                Boleteria.pack();
                Boleteria.setLocationRelativeTo(this);
                Boleteria.setVisible(true);
            } else if (cargo.equals("Aseo")) {
                System.out.println(cargo);
                Aseo.setModal(true);
                Aseo.pack();
                Aseo.setLocationRelativeTo(this);
                Aseo.setVisible(true);
            }
            }
        }
    }//GEN-LAST:event_CredencialesMouseClicked

    private void CempleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CempleMouseClicked
        CreaEmple.setModal(true);
        CreaEmple.pack();
        CreaEmple.setLocationRelativeTo(this);
        CreaEmple.setVisible(true);
    }//GEN-LAST:event_CempleMouseClicked

    private void CNempleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CNempleMouseClicked

        String Nombre = Nnombre.getText();
        Date fecha = FechaEmple.getDate();
        String Nusuario=this.NUsuario.getText();
        String puesto=(String)CB_puesto.getSelectedItem();
        String Contra=CContra.getText();
        String Correo=CCorreo.getText();
        emple.add(new Empleados(Nombre, fecha, Nusuario, Contra, Correo, puesto));
        JOptionPane.showMessageDialog(Cemple, "empleado creado exitosamente");
        Nnombre.setText("");
        NUsuario.setText("");
        CContra.setText("");
        CCorreo.setText("");
        
        
    }//GEN-LAST:event_CNempleMouseClicked

    private void CreaDulceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CreaDulceKeyPressed
        // TODO add your handling code here:
        String Ndulce=Ndulc.getText();
        String sabor=Nsabor.getText();
        String tipo=(String)CB_tipo.getSelectedItem();
        Ndulc.setText("");
        Nsabor.setText("");
        
    }//GEN-LAST:event_CreaDulceKeyPressed

    private void dulcesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dulcesMouseClicked
        CrearDulce.setModal(true);
        CrearDulce.pack();
        CrearDulce.setLocationRelativeTo(this);
        CrearDulce.setVisible(true);
    }//GEN-LAST:event_dulcesMouseClicked

    private void btcrearpeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcrearpeliMouseClicked
        Cpeli.setModal(true);
        Cpeli.pack();
        Cpeli.setLocationRelativeTo(this);
        Cpeli.setVisible(true);
    }//GEN-LAST:event_btcrearpeliMouseClicked

    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Aseo;
    private javax.swing.JDialog Boleteria;
    private javax.swing.JComboBox<String> CB_puesto;
    private javax.swing.JComboBox<String> CB_tipo;
    private javax.swing.JTextField CContra;
    private javax.swing.JTextField CCorreo;
    private javax.swing.JButton CNemple;
    private javax.swing.JButton Cemple;
    private javax.swing.JDialog Cpeli;
    private javax.swing.JButton CreaDulce;
    private javax.swing.JDialog CreaEmple;
    private javax.swing.JButton CreaPeli;
    private javax.swing.JDialog CrearDulce;
    private javax.swing.JButton Credenciales;
    private javax.swing.JDialog Dulceria;
    private com.toedter.calendar.JDateChooser FechaEmple;
    private javax.swing.JButton LOGINP;
    private javax.swing.JDialog LogIn;
    private javax.swing.JDialog Madmin;
    private javax.swing.JTextField NPeli;
    private javax.swing.JTextField NUsuario;
    private javax.swing.JTextField Ndulc;
    private javax.swing.JTextField Nnombre;
    private javax.swing.JTextField Nsabor;
    private javax.swing.JTextField USUlog;
    private javax.swing.JButton btcrearpeli;
    private javax.swing.JPasswordField contralog;
    private javax.swing.JButton dulces;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
ArrayList<Empleados> emple = new ArrayList();
ArrayList<Dulces> dulce = new ArrayList();
ArrayList<peliculas> peli = new ArrayList();
ArrayList<Aseo> aseo = new ArrayList();

}
